---

channel_triton: '10.249.6.23:8001'
channel_seerep: 'agrigaia-ur.ni.dfki:9090'
seerep_project: 'aitf-triton-data'
model_name: 'dino_coco_600_squared'
model_version: '' 
log_level: 'critical'
batch_size: 1
visualize: false
semantics: 
 - person
 - weatherGeneral_cloudy